# Generated by Django 4.2.7 on 2023-11-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100)),
                ('clock', models.IntegerField(default=0)),
                ('is_on_hold', models.BooleanField(default=False)),
            ],
        ),
    ]
