# Generated by Django 4.2.7 on 2023-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomclock',
            name='threshold',
            field=models.IntegerField(default=120),
        ),
    ]
